/**
 * Compose reload + base-snapshot helpers shared by add-page and upgrade.
 *
 * Snapshots live at `.cronus-ui/base/<composedKey>/` (the `composed{}` key =
 * template name). Pre-F4 compose wrote them under the package.json name
 * (`plan.appName`); readers fall back to that dir when the composed-key dir
 * (or a given file in it) is missing. New writes always use the composed key.
 */

import { existsSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import type { ComposedRecord } from "../config.js";
import { resolveSafeDest } from "../utils.js";
import { type AppManifest, manifestFingerprint } from "./manifest.js";
import { loadManifestFile, loadTemplate } from "./templates.js";

/** Base-snapshot directory for an app's generated bytes (F4 merge base). */
export function baseSnapshotDir(appKey: string): string {
  return join(".cronus-ui", "base", appKey);
}

/** Keys to try when reading a snapshot: composed key first, then legacy appName. */
function snapshotReadKeys(composedKey: string, appName: string): string[] {
  if (appName.length === 0 || appName === composedKey) return [composedKey];
  return [composedKey, appName];
}

/**
 * Absolute dest of a snapshot file for a NEW write. Always the composed key —
 * never the legacy package-name dir.
 */
export function baseSnapshotDest(cwd: string, composedKey: string, relPath: string): string {
  return resolveSafeDest(cwd, baseSnapshotDir(composedKey), relPath);
}

/**
 * Read one snapshot file. Prefers `.cronus-ui/base/<composedKey>/<rel>`; if that
 * file is missing, falls back to `.cronus-ui/base/<appName>/<rel>` (legacy
 * compose). Returns undefined when neither exists.
 */
export async function readBaseSnapshot(
  cwd: string,
  composedKey: string,
  appName: string,
  relPath: string,
): Promise<string | undefined> {
  for (const key of snapshotReadKeys(composedKey, appName)) {
    let dest: string;
    try {
      dest = resolveSafeDest(cwd, baseSnapshotDir(key), relPath);
    } catch {
      continue;
    }
    if (existsSync(dest)) return readFile(dest, "utf8");
  }
  return undefined;
}

/** Recursively list files under `dir` as paths relative to `dir`. */
async function walkRelFiles(dir: string, prefix = ""): Promise<string[]> {
  const out: string[] = [];
  try {
    const entries = await readdir(dir, { withFileTypes: true, encoding: "utf8" });
    for (const entry of entries) {
      const rel = prefix === "" ? entry.name : join(prefix, entry.name);
      if (entry.isDirectory()) {
        out.push(...(await walkRelFiles(join(dir, entry.name), rel)));
      } else if (entry.isFile()) {
        out.push(rel);
      }
    }
  } catch {
    return out;
  }
  return out;
}

/**
 * Rel paths present in the snapshot tree(s). Unions the composed-key dir with
 * the legacy appName dir when both exist, so a mixed pre/post-fix project
 * still sees every snapshotted file.
 */
export async function listBaseSnapshotRels(
  cwd: string,
  composedKey: string,
  appName: string,
): Promise<string[]> {
  const rels = new Set<string>();
  for (const key of snapshotReadKeys(composedKey, appName)) {
    const dir = join(cwd, baseSnapshotDir(key));
    if (!existsSync(dir)) continue;
    for (const rel of await walkRelFiles(dir)) rels.add(rel);
  }
  return [...rels];
}

/**
 * Reload the app's manifest: an explicit `--manifest` file wins, else the bundled
 * template whose name equals the composed key. A `--manifest`-composed app whose
 * name is not a bundled template must re-supply `--manifest` (its manifest is not
 * recoverable from `composed{}` alone) — we fail loud with that hint.
 *
 * PROVENANCE GUARD: the bundled fallback is keyed only on the app NAME, but a
 * `--manifest`-composed app is keyed by the manifest's own `name` field, which can
 * COLLIDE with a bundled template name (store/landing/saas). In that case
 * `loadTemplate` silently returns the WRONG (bundled) manifest, and a re-plan
 * would then drop every composed route/chrome group that the bundled template does
 * not declare — silently corrupting the nav + composed record. So we verify the
 * reloaded bundled template's content fingerprint against the compose-time
 * `manifestHash` provenance recorded in `composed{}` and fail loud on a mismatch,
 * demanding `--manifest`. A legacy record (composed before provenance existed) has
 * no hash to check, so that case falls back to the prior lenient behavior.
 */
export async function reloadManifest(
  appName: string,
  manifestPath: string | undefined,
  composed: ComposedRecord,
): Promise<AppManifest> {
  if (manifestPath !== undefined) return loadManifestFile(manifestPath);
  let bundled: AppManifest;
  try {
    bundled = await loadTemplate(appName);
  } catch (err) {
    throw new Error(
      `Cannot reload the manifest for composed app "${appName}": it is not a bundled template. ` +
        `Pass --manifest <file> pointing at the manifest it was composed from. (${(err as Error).message})`,
    );
  }
  // Verify provenance: the recorded hash (from compose) must equal the reloaded
  // bundled template's fingerprint. A mismatch means this app was composed from a
  // DIFFERENT manifest whose name collides with the bundled template.
  const recorded = composed.manifestHash;
  if (recorded !== undefined && recorded !== manifestFingerprint(bundled)) {
    throw new Error(
      `The bundled template "${appName}" is not the manifest app "${appName}" was composed from ` +
        `(provenance hash mismatch). This app was composed from a custom --manifest whose name collides ` +
        `with a bundled template. Re-run with --manifest <file> pointing at that manifest.`,
    );
  }
  return bundled;
}

/**
 * Restrict a reloaded manifest to the pages this app actually composed
 * (`composed.choices.pages`, preserving manifest order). Add-page grafts that
 * are not in the bundled/reloaded template are omitted from the synthetic
 * manifest (they have no upstream render) — callers must keep them in
 * `choices.pages` and on disk.
 */
export function filterManifestToComposedPages(
  base: AppManifest,
  composed: ComposedRecord,
): AppManifest {
  const composedRoutes = new Set(composed.choices.pages);
  const pages = base.manifest.pages.filter((p) => composedRoutes.has(p.route));
  return { ...base, manifest: { ...base.manifest, pages } };
}
