import type { ParityFixture } from "./parity-fixture.js";

const FAMILY_TAGS: Record<string, string> = {
  badge: "span",
  input: "input",
  label: "label",
  textarea: "textarea",
  checkbox: "button",
  switch: "button",
  spinner: "svg",
  separator: "div",
  kbd: "kbd",
  toggle: "button",
  progress: "div",
  alert: "div",
  skeleton: "div",
  banner: "section",
  slider: "span",
  "radio-group": "div",
  chip: "span",
  avatar: "span",
  card: "div",
  empty: "div",
  field: "div",
  "input-group": "div",
  rating: "div",
  "copy-button": "button",
  fab: "div",
  "toggle-group": "div",
  metric: "div",
  "avatar-group": "div",
  "button-group": "div",
  combobox: "button",
  stepper: "div",
  "input-otp": "input",
  "file-dropzone": "label",
  popover: "div",
  "hover-card": "div",
  "dropdown-menu": "div",
  collapsible: "div",
  "mode-toggle": "button",
  command: "div",
  menubar: "div",
  "context-menu": "div",
  drawer: "div",
  sheet: "div",
  calendar: "div",
  "date-picker": "button",
  "time-picker": "button",
  "date-range-picker": "button",
  "area-chart": "div",
  "bar-chart": "div",
  "line-chart": "div",
  sparkline: "svg",
  "pie-chart": "div",
  "data-table": "div",
  sidebar: "aside",
  sonner: "div",
  "navigation-menu": "nav",
  "radar-chart": "div",
  "scatter-chart": "div",
  "ring-chart": "div",
  "phone-input": "div",
  "currency-input": "div",
  "color-picker": "button",
  "scroll-area": "div",
  toolbar: "div",
  "status-dot": "span",
  "tags-input": "div",
  autocomplete: "div",
  "multi-select": "div",
  "credit-card-input": "div",
  "floating-label-input": "div",
  "split-button": "div",
  "pill-nav": "nav",
  dock: "div",
  "workspace-switcher": "button",
  "app-shell": "div",
  "table-of-contents": "nav",
  form: "div",
  "signature-pad": "div",
  resizable: "div",
  scheduler: "div",
  "alert-dialog": "div",
  lightbox: "div",
  "notification-center": "div",
  "segmented-control": "div",
  "usage-meter": "div",
  masonry: "div",
  heatmap: "div",
  "comparison-slider": "div",
  "code-tabs": "div",
  "expandable-tabs": "div",
  "live-line-chart": "div",
  "sunburst-chart": "div",
  "choropleth-chart": "div",
  "profit-loss-chart": "div",
  "scroll-progress": "div",
  "rich-text-editor": "div",
  "confirmation-dialog": "div",
  "invite-dialog": "div",
  shimmer: "div",
  reveal: "div",
  "text-shimmer": "p",
  particles: "div",
  "sparkles-text": "span",
  noise: "div",
  "morphing-popover": "div",
  "bouncy-accordion": "div",
  "typing-text": "span",
  "word-rotate": "span",
  timeline: "ol",
  "tree-view": "div",
  "tilt-card": "div",
  "star-border": "div",
  "glass-card": "div",
  terminal: "div",
  "video-player": "div",
  "text-effect": "p",
  "spotlight-card": "div",
  "animated-list": "ul",
  toast: "div",
  carousel: "div",
  "code-block": "div",
  "description-list": "dl",
  kanban: "div",
  "json-viewer": "div",
  "animated-number": "span",
  marquee: "div",
  "gradient-text": "span",
  "shiny-text": "span",
  "aspect-ratio": "div",
  frame: "div",
  "flip-card": "div",
  countdown: "div",
  "animated-button": "button",
  "card-stack": "section",
  "gauge-chart": "div",
  "funnel-chart": "div",
  "candlestick-chart": "div",
  "logo-carousel": "ul",
  "dynamic-island": "div",
  "image-zoom": "button",
  "aurora-background": "div",
  "border-beam": "div",
  confetti: "div",
  "composed-chart": "div",
  "heatmap-chart": "div",
  chart: "div",
  "click-spark": "div",
  "glare-hover": "div",
  magnetic: "div",
  "dot-pattern": "div",
  "flickering-grid": "div",
  "grid-pattern": "div",
  highlighter: "span",
  "scramble-text": "span",
  "spinning-text": "div",
  "gradient-border": "div",
  "light-rays": "div",
  orbit: "div",
  "progressive-blur": "div",
  "retro-grid": "div",
  ripple: "div",
  "motion-presets": "div",
};

/** Attrs the React component actually emits. Never require `data-size`. */
export function expectedReactAttrs(fixture: ParityFixture): Record<string, string> {
  const attrs: Record<string, string> = { ...(fixture.expect.attrs ?? {}) };
  delete attrs["data-size"];
  attrs["data-slot"] = fixture.expect.slot;
  if (fixture.family === "button" || fixture.family === "badge") {
    const variant =
      typeof fixture.props.variant === "string"
        ? fixture.props.variant
        : fixture.family === "badge"
          ? "default"
          : "primary";
    attrs["data-variant"] = attrs["data-variant"] ?? variant;
  }
  return attrs;
}

export function expectedTag(fixture: ParityFixture): string {
  if (fixture.expect.tag) return fixture.expect.tag;
  if (fixture.family === "button") {
    return typeof fixture.props.href === "string" ? "a" : "button";
  }
  return FAMILY_TAGS[fixture.family] ?? "div";
}
