/** True for the templates that ship a database and need `db:push` before `dev`. */
export function isGoldPathTemplate(name: string): boolean {
  return name === "saas" || name === "admin";
}

/**
 * The starter templates a user can pick. `default`/`dashboard`/`marketing` copy
 * a bundled directory under `templates/`; `store`/`landing`/`saas` have NO
 * template dir — they scaffold the `default` base and then compose validated
 * blocks on top (see {@link TEMPLATE_BASE_DIR} and the post-scaffold
 * `composeApp()` step).
 */
/**
 * Product landing flavors (compose apps). Each is a distinctive stack of
 * validated marketing blocks + a theme/mode default — not a bundled directory.
 * `landing` stays the generic marketing page; these are the named flavors.
 */
export const LANDING_FLAVORS = [
  "landing-studio",
  "landing-ops",
  "landing-secure",
  "landing-care",
  "landing-shop",
  "landing-docs",
  "landing-premium",
  "landing-agents",
  "landing-coverage",
  "landing-broadcast",
  "landing-agency",
  "landing-glass",
] as const;
export type LandingFlavor = (typeof LANDING_FLAVORS)[number];

/**
 * Pro compose apps. Additive product surfaces (mail, chat, finance) — not
 * landings. OSS keeps saas/store/landing; these are the Pro pack.
 */
export const PRO_APPS = ["mail", "chat", "finance"] as const;
export type ProApp = (typeof PRO_APPS)[number];

export const TEMPLATES = [
  "default",
  "dashboard",
  "marketing",
  "gontify",
  "portfolio",
  "store",
  "landing",
  "saas",
  "admin",
  "docs",
  ...LANDING_FLAVORS,
  ...PRO_APPS,
] as const;
export type TemplateName = (typeof TEMPLATES)[number];
export const DEFAULT_TEMPLATE: TemplateName = "saas";

/**
 * The template names generated by the Cronus Compose app generator (no bundled
 * dir): they scaffold the `default` base, then `composeApp()` from the bundled
 * manifest renders the pages + chrome from validated blocks. The value is the
 * manifest/template name passed to `composeApp`.
 */
export const COMPOSED_TEMPLATES = {
  store: "store",
  landing: "landing",
  saas: "saas",
  admin: "admin",
  docs: "docs",
  "landing-studio": "landing-studio",
  "landing-ops": "landing-ops",
  "landing-secure": "landing-secure",
  "landing-care": "landing-care",
  "landing-shop": "landing-shop",
  "landing-docs": "landing-docs",
  "landing-premium": "landing-premium",
  "landing-agents": "landing-agents",
  "landing-coverage": "landing-coverage",
  "landing-broadcast": "landing-broadcast",
  "landing-agency": "landing-agency",
  "landing-glass": "landing-glass",
  mail: "mail",
  chat: "chat",
  finance: "finance",
} as const satisfies Partial<Record<TemplateName, string>>;

export type ComposedTemplateName = keyof typeof COMPOSED_TEMPLATES;

/** True when `template` is generated by the composer (no bundled dir). */
export function isComposedTemplate(template: TemplateName): template is ComposedTemplateName {
  return template in COMPOSED_TEMPLATES;
}

/**
 * The bundled base directory each template copies before any composition.
 * Composed templates (`store`/`landing`/`saas`) reuse the `default` base; the
 * others are their own name.
 */
export function templateBaseDir(template: TemplateName): TemplateName {
  return isComposedTemplate(template) ? "default" : template;
}

/** One-line summary per template, shown in the picker. */
export const TEMPLATE_HINTS: Record<TemplateName, string> = {
  default: "single-page starter — metrics, table & cards (default)",
  dashboard: "multi-page app — sidebar shell, KPIs, chart, data table, settings",
  marketing: "landing site — hero, features, pricing, testimonials, FAQ, waitlist",
  gontify: "AI SaaS landing — column-line hero, flowing logos, kinetic testimonials",
  portfolio: "personal portfolio — work, projects, community, pixel theme toggle",
  store: "generated storefront — 9 navigable pages, real nav, from validated blocks",
  landing: "generated landing page — hero, features, pricing, testimonials, FAQ, CTA",
  saas: "recommended for a full product — split auth + shell dashboard, team, billing, settings",
  admin:
    "admin console — split login + shell, overview, users, analytics, board, audit (midnight dark)",
  docs: "docs site — changelog, guides, article, FAQ, about — not a marketing landing (neutral light)",
  "landing-studio": "dark AI studio landing — atmosphere hero, marquee, bento, stats, pricing",
  "landing-ops": "ops/workflow landing — split hero, logos, features, integrations",
  "landing-secure": "security/infra landing — compact hero, metrics, usage pricing, split FAQ",
  "landing-care": "healthcare/conversion landing — waitlist hero, bento, proof (emerald light)",
  "landing-shop": "storefront landing — compact hero + editorial product showcase (sunset light)",
  "landing-docs": "developer-tool landing — compact hero, logos, features, integrations",
  "landing-premium": "full SaaS marketing page — split hero, toggle pricing, FAQ (aurora light)",
  "landing-agents": "automation landing — split hero, marquee, bento, stats (emerald light)",
  "landing-coverage": "services landing — hero, stats, testimonial grid, FAQ (sunset light)",
  "landing-broadcast": "studio/show landing — atmosphere hero, marquee logos, features, pricing",
  "landing-agency": "agency landing — split hero, about, services, stats (midnight dark)",
  "landing-glass": "glass-dark landing — atmosphere hero, bento, split FAQ, split CTA",
  mail: "Pro inbox — notification panel, activity feed, compose, preferences (midnight dark)",
  chat: "Pro assistant — chat thread, prompt box, replies, settings (aurora dark)",
  finance: "Pro money app — payouts, invoices, billing, analytics (emerald light)",
};

/** The five shipped theme presets (must match @cronus-ui/tokens `ThemeName`). */
export const THEMES = ["aurora", "neutral", "midnight", "sunset", "emerald"] as const;
export type Theme = (typeof THEMES)[number];
export const DEFAULT_THEME: Theme = "aurora";

/** One-line vibe per theme, shown in the picker. */
export const THEME_HINTS: Record<Theme, string> = {
  aurora: "sky → cyan premium gradient (default)",
  neutral: "clean black & white — docs-site chrome, achromatic",
  midnight: "deep indigo / violet",
  sunset: "warm amber / rose",
  emerald: "fresh green / teal",
};

/** Color modes the provider supports natively (no built-in "system"). */
export const MODES = ["dark", "light"] as const;
export type ModeName = (typeof MODES)[number];
export const DEFAULT_MODE: ModeName = "dark";

/** Theme/mode baked when the user picks a landing flavor without `--theme`/`--mode`. */
export const TEMPLATE_APPEARANCE: Partial<Record<TemplateName, { theme: Theme; mode: ModeName }>> =
  {
    "landing-studio": { theme: "midnight", mode: "dark" },
    "landing-ops": { theme: "aurora", mode: "dark" },
    "landing-secure": { theme: "midnight", mode: "dark" },
    "landing-care": { theme: "emerald", mode: "light" },
    "landing-shop": { theme: "sunset", mode: "light" },
    "landing-docs": { theme: "aurora", mode: "dark" },
    "landing-premium": { theme: "aurora", mode: "light" },
    "landing-agents": { theme: "emerald", mode: "light" },
    "landing-coverage": { theme: "sunset", mode: "light" },
    "landing-broadcast": { theme: "aurora", mode: "dark" },
    "landing-agency": { theme: "midnight", mode: "dark" },
    "landing-glass": { theme: "midnight", mode: "dark" },
    mail: { theme: "midnight", mode: "dark" },
    chat: { theme: "aurora", mode: "dark" },
    finance: { theme: "emerald", mode: "light" },
    admin: { theme: "midnight", mode: "dark" },
    docs: { theme: "neutral", mode: "light" },
    gontify: { theme: "neutral", mode: "dark" },
    portfolio: { theme: "neutral", mode: "light" },
  };
