/** Supported package managers, in detection-fallback order. */
export const PACKAGE_MANAGERS = ["bun", "npm", "pnpm", "yarn"] as const;
export type PackageManager = (typeof PACKAGE_MANAGERS)[number];

// Minimal ANSI helpers — no dependency needed. Colors are dropped when stdout
// is not a TTY or NO_COLOR is set, so piped/CI output stays clean.
const useColor = Boolean(process.stdout.isTTY) && !process.env.NO_COLOR;
const wrap = (open: number, close: number) => (s: string) =>
  useColor ? `[${open}m${s}[${close}m` : s;

export const c = {
  bold: wrap(1, 22),
  dim: wrap(2, 22),
  green: wrap(32, 39),
  yellow: wrap(33, 39),
  red: wrap(31, 39),
  cyan: wrap(36, 39),
  magenta: wrap(35, 39),
};

/**
 * Next-step lines printed after a successful scaffold. Pure so tests can assert
 * the copy without scraping stdout. `template` is optional for back-compat: omit
 * it (or pass a bundled template) to keep the component-add path; composed
 * templates (`saas`/`store`/`landing`) get add-page / theme / upgrade instead.
 */
export function outroLines(
  name: string,
  pm: PackageManager,
  installed: boolean,
  template?: TemplateName,
): string[] {
  const dev = pm === "npm" ? "npm run dev" : `${pm} dev`;
  const install = pm === "yarn" ? "yarn" : `${pm} install`;
  const dollar = c.dim("$");
  const composed = template !== undefined && isComposedTemplate(template);
  const grow = composed
    ? [
        "Grow the app anytime:",
        `  ${dollar} npx cronus-ui add-page --route /pricing --blocks pricing,cta --nav Pricing`,
        `  ${dollar} npx cronus-ui theme set aurora --mode dark`,
        `  ${dollar} npx cronus-ui upgrade --all --dry-run`,
      ]
    : [
        `Add more components anytime:  ${dollar} npx cronus-ui add dialog table tabs`,
        `Want a multi-page app?        ${dollar} npx cronus-ui compose saas`,
      ];
  return [
    "",
    `${c.green(c.bold("Done!"))} Your Cronus UI app is ready in ${c.cyan(name)}.`,
    "",
    "Next steps:",
    `  ${dollar} cd ${name}`,
    ...(installed ? [] : [`  ${dollar} ${install}`]),
    `  ${dollar} ${dev}`,
    "",
    `Then open ${c.cyan("http://localhost:3000")}.`,
    "",
    ...grow,
    "",
  ];
}

export const log = {
  intro(): void {
    process.stdout.write(`\n${c.magenta(c.bold("create-cronus-app"))}\n\n`);
  },
  step(msg: string): void {
    process.stdout.write(`${c.cyan("›")} ${msg}\n`);
  },
  ok(msg: string): void {
    process.stdout.write(`${c.green("✓")} ${msg}\n`);
  },
  warn(msg: string): void {
    process.stdout.write(`${c.yellow("!")} ${msg}\n`);
  },
  error(msg: string): void {
    process.stderr.write(`${c.red("✗")} ${msg}\n`);
  },
  outro(name: string, pm: PackageManager, installed: boolean, template?: TemplateName): void {
    process.stdout.write(`${outroLines(name, pm, installed, template).join("\n")}\n`);
  },
};

/**
 * The starter templates a user can pick. `default`/`dashboard`/`marketing` copy
 * a bundled directory under `templates/`; `store`/`landing`/`saas` have NO
 * template dir — they scaffold the `default` base and then compose validated
 * blocks on top (see {@link TEMPLATE_BASE_DIR} and the post-scaffold
 * `composeApp()` step).
 */
/**
 * Product landing flavors (compose apps). Each is a distinctive stack of
 * validated marketing blocks + a theme/mode default — not a bundled directory.
 * `landing` stays the generic marketing page; these are the named flavors.
 */
export const LANDING_FLAVORS = [
  "landing-studio",
  "landing-ops",
  "landing-secure",
  "landing-care",
  "landing-shop",
  "landing-docs",
  "landing-premium",
  "landing-agents",
  "landing-coverage",
  "landing-broadcast",
  "landing-agency",
  "landing-glass",
] as const;
export type LandingFlavor = (typeof LANDING_FLAVORS)[number];

/**
 * Pro compose apps. Additive product surfaces (mail, chat, finance) — not
 * landings. OSS keeps saas/store/landing; these are the Pro pack.
 */
export const PRO_APPS = ["mail", "chat", "finance"] as const;
export type ProApp = (typeof PRO_APPS)[number];

export const TEMPLATES = [
  "default",
  "dashboard",
  "marketing",
  "store",
  "landing",
  "saas",
  "admin",
  "docs",
  ...LANDING_FLAVORS,
  ...PRO_APPS,
] as const;
export type TemplateName = (typeof TEMPLATES)[number];
export const DEFAULT_TEMPLATE: TemplateName = "default";

/**
 * The template names generated by the Cronus Compose app generator (no bundled
 * dir): they scaffold the `default` base, then `composeApp()` from the bundled
 * manifest renders the pages + chrome from validated blocks. The value is the
 * manifest/template name passed to `composeApp`.
 */
export const COMPOSED_TEMPLATES = {
  store: "store",
  landing: "landing",
  saas: "saas",
  admin: "admin",
  docs: "docs",
  "landing-studio": "landing-studio",
  "landing-ops": "landing-ops",
  "landing-secure": "landing-secure",
  "landing-care": "landing-care",
  "landing-shop": "landing-shop",
  "landing-docs": "landing-docs",
  "landing-premium": "landing-premium",
  "landing-agents": "landing-agents",
  "landing-coverage": "landing-coverage",
  "landing-broadcast": "landing-broadcast",
  "landing-agency": "landing-agency",
  "landing-glass": "landing-glass",
  mail: "mail",
  chat: "chat",
  finance: "finance",
} as const satisfies Partial<Record<TemplateName, string>>;

export type ComposedTemplateName = keyof typeof COMPOSED_TEMPLATES;

/** True when `template` is generated by the composer (no bundled dir). */
export function isComposedTemplate(template: TemplateName): template is ComposedTemplateName {
  return template in COMPOSED_TEMPLATES;
}

/**
 * The bundled base directory each template copies before any composition.
 * Composed templates (`store`/`landing`/`saas`) reuse the `default` base; the
 * others are their own name.
 */
export function templateBaseDir(template: TemplateName): TemplateName {
  return isComposedTemplate(template) ? "default" : template;
}

/** One-line summary per template, shown in the picker. */
export const TEMPLATE_HINTS: Record<TemplateName, string> = {
  default: "single-page starter — metrics, table & cards (default)",
  dashboard: "multi-page app — sidebar shell, KPIs, chart, data table, settings",
  marketing: "landing site — hero, features, pricing, testimonials, FAQ, waitlist",
  store: "generated storefront — 9 navigable pages, real nav, from validated blocks",
  landing: "generated landing page — hero, features, pricing, testimonials, FAQ, CTA",
  saas: "recommended for a full product — split auth + shell dashboard, team, billing, settings",
  admin:
    "admin console — split login + shell, overview, users, analytics, board, audit (midnight dark)",
  docs: "docs site — changelog, guides, article, FAQ, about — not a marketing landing (neutral light)",
  "landing-studio": "dark AI studio landing — atmosphere hero, marquee, bento, stats, pricing",
  "landing-ops": "ops/workflow landing — split hero, logos, features, integrations",
  "landing-secure": "security/infra landing — compact hero, metrics, usage pricing, split FAQ",
  "landing-care": "healthcare/conversion landing — waitlist hero, bento, proof (emerald light)",
  "landing-shop": "storefront landing — compact hero + editorial product showcase (sunset light)",
  "landing-docs": "developer-tool landing — compact hero, logos, features, integrations",
  "landing-premium": "full SaaS marketing page — split hero, toggle pricing, FAQ (aurora light)",
  "landing-agents": "automation landing — split hero, marquee, bento, stats (emerald light)",
  "landing-coverage": "services landing — hero, stats, testimonial grid, FAQ (sunset light)",
  "landing-broadcast": "studio/show landing — atmosphere hero, marquee logos, features, pricing",
  "landing-agency": "agency landing — split hero, about, services, stats (midnight dark)",
  "landing-glass": "glass-dark landing — atmosphere hero, bento, split FAQ, split CTA",
  mail: "Pro inbox — notification panel, activity feed, compose, preferences (midnight dark)",
  chat: "Pro assistant — chat thread, prompt box, replies, settings (aurora dark)",
  finance: "Pro money app — payouts, invoices, billing, analytics (emerald light)",
};

/** The five shipped theme presets (must match @cronus-ui/tokens `ThemeName`). */
export const THEMES = ["aurora", "neutral", "midnight", "sunset", "emerald"] as const;
export type Theme = (typeof THEMES)[number];
export const DEFAULT_THEME: Theme = "aurora";

/** One-line vibe per theme, shown in the picker. */
export const THEME_HINTS: Record<Theme, string> = {
  aurora: "sky → cyan premium gradient (default)",
  neutral: "clean black & white — docs-site chrome, achromatic",
  midnight: "deep indigo / violet",
  sunset: "warm amber / rose",
  emerald: "fresh green / teal",
};

/** Color modes the provider supports natively (no built-in "system"). */
export const MODES = ["dark", "light"] as const;
export type ModeName = (typeof MODES)[number];
export const DEFAULT_MODE: ModeName = "dark";

/** Theme/mode baked when the user picks a landing flavor without `--theme`/`--mode`. */
export const TEMPLATE_APPEARANCE: Partial<Record<TemplateName, { theme: Theme; mode: ModeName }>> =
  {
    "landing-studio": { theme: "midnight", mode: "dark" },
    "landing-ops": { theme: "aurora", mode: "dark" },
    "landing-secure": { theme: "midnight", mode: "dark" },
    "landing-care": { theme: "emerald", mode: "light" },
    "landing-shop": { theme: "sunset", mode: "light" },
    "landing-docs": { theme: "aurora", mode: "dark" },
    "landing-premium": { theme: "aurora", mode: "light" },
    "landing-agents": { theme: "emerald", mode: "light" },
    "landing-coverage": { theme: "sunset", mode: "light" },
    "landing-broadcast": { theme: "aurora", mode: "dark" },
    "landing-agency": { theme: "midnight", mode: "dark" },
    "landing-glass": { theme: "midnight", mode: "dark" },
    mail: { theme: "midnight", mode: "dark" },
    chat: { theme: "aurora", mode: "dark" },
    finance: { theme: "emerald", mode: "light" },
    admin: { theme: "midnight", mode: "dark" },
    docs: { theme: "neutral", mode: "light" },
  };

/**
 * A single-select TTY prompt: prints a numbered list and returns the option the
 * user picks (by number or name), the default on empty input, or the default
 * verbatim when stdin is not a TTY (piped/CI) so scaffolding never blocks.
 */
export async function promptSelect<T extends string>(
  label: string,
  options: readonly T[],
  defaultValue: T,
  hints?: Partial<Record<T, string>>,
): Promise<T> {
  if (!process.stdin.isTTY) return defaultValue;
  const { createInterface } = await import("node:readline/promises");
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    process.stdout.write(`${c.bold(label)}\n`);
    options.forEach((opt, i) => {
      const marker = opt === defaultValue ? c.green("●") : c.dim("○");
      const hint = hints?.[opt] ? `  ${c.dim(hints[opt] as string)}` : "";
      process.stdout.write(`  ${marker} ${c.cyan(String(i + 1))} ${opt}${hint}\n`);
    });
    const answer = (
      await rl.question(`${c.dim(`(1-${options.length} or name, default ${defaultValue})`)} `)
    ).trim();
    if (!answer) return defaultValue;
    const asNum = Number.parseInt(answer, 10);
    if (Number.isInteger(asNum) && asNum >= 1 && asNum <= options.length) {
      return options[asNum - 1] as T;
    }
    const byName = options.find((o) => o === answer.toLowerCase());
    return byName ?? defaultValue;
  } finally {
    rl.close();
  }
}

/**
 * A yes/no TTY prompt. Returns `defaultValue` on empty input or when stdin is
 * not a TTY (piped/CI), so scaffolding never blocks on a confirmation.
 */
export async function promptConfirm(label: string, defaultValue = true): Promise<boolean> {
  if (!process.stdin.isTTY) return defaultValue;
  const { createInterface } = await import("node:readline/promises");
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const hint = defaultValue ? "Y/n" : "y/N";
    const answer = (await rl.question(`${c.bold(label)} ${c.dim(`(${hint})`)} `))
      .trim()
      .toLowerCase();
    if (!answer) return defaultValue;
    return answer === "y" || answer === "yes";
  } finally {
    rl.close();
  }
}

// npm's package-name rules (the spec subset we care about): optionally scoped,
// lowercase, URL-safe, may not start with "." or "_", <= 214 chars.
const SCOPED = /^(?:@[a-z0-9-~][a-z0-9-._~]*\/)?[a-z0-9-~][a-z0-9-._~]*$/;

/** Validate that `name` is safe to use as an npm package name and a dir name. */
export function isValidProjectName(name: string): boolean {
  if (!name || name.length > 214) return false;
  if (name.trim() !== name) return false;
  // Reject path separators outright (a scoped name's single "/" is allowed by
  // the regex, but the literal dir is the unscoped trailing segment).
  if (name.includes("\\")) return false;
  return SCOPED.test(name);
}

/**
 * Derive the on-disk directory name from a (possibly scoped) package name:
 * "@acme/widget" → "widget", "my-app" → "my-app".
 */
export function dirNameFromProjectName(name: string): string {
  const slash = name.lastIndexOf("/");
  return slash === -1 ? name : name.slice(slash + 1);
}
