// GENERATED by packages/tokens/scripts/build-tokens.ts from src/tokens.ts — do not edit by hand.
import type { Config } from "tailwindcss";

/**
 * Cronus Tailwind preset. Maps semantic utilities (bg-primary, rounded-lg,
 * shadow-glow, text-fg-secondary, …) to the runtime `--cronus-*` variables
 * defined in `@cronus-ui/tokens/styles.css`, so they re-theme live.
 */
declare const preset: Config;
export default preset;
