// GENERATED by packages/tokens/scripts/build-tokens.ts from src/tokens.ts — do not edit by hand.
/** @type {import("tailwindcss").Config} */
const preset = {
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "var(--kronus-primary)",
          foreground: "var(--kronus-primary-foreground)",
          strong: "var(--kronus-primary-text)",
        },
        accent: {
          DEFAULT: "var(--kronus-accent)",
          foreground: "var(--kronus-accent-foreground)",
        },
        surface: {
          base: "var(--kronus-surface-base)",
          inset: "var(--kronus-surface-inset)",
          raised: "var(--kronus-surface-raised)",
          overlay: "var(--kronus-surface-overlay)",
          elevated: "var(--kronus-surface-elevated)",
          floating: "var(--kronus-surface-floating)",
        },
        fg: {
          DEFAULT: "var(--kronus-fg)",
          secondary: "var(--kronus-fg-secondary)",
          tertiary: "var(--kronus-fg-tertiary)",
          muted: "var(--kronus-fg-muted)",
          inverse: "var(--kronus-fg-inverse)",
        },
        border: {
          DEFAULT: "var(--kronus-border)",
          strong: "var(--kronus-border-strong)",
          soft: "var(--kronus-border-soft)",
        },
        ring: "var(--kronus-ring)",
        success: {
          DEFAULT: "var(--kronus-success)",
          strong: "var(--kronus-success-text)",
        },
        warning: {
          DEFAULT: "var(--kronus-warning)",
          strong: "var(--kronus-warning-text)",
        },
        error: {
          DEFAULT: "var(--kronus-error)",
          strong: "var(--kronus-error-text)",
        },
        info: {
          DEFAULT: "var(--kronus-info)",
          strong: "var(--kronus-info-text)",
        },
        chart: {
          1: "var(--kronus-chart-1)",
          2: "var(--kronus-chart-2)",
          3: "var(--kronus-chart-3)",
          4: "var(--kronus-chart-4)",
          5: "var(--kronus-chart-5)",
        },
      },
      borderRadius: {
        sm: "max(0px, calc(var(--kronus-radius) - 8px))",
        md: "max(0px, calc(var(--kronus-radius) - 4px))",
        lg: "var(--kronus-radius)",
        xl: "calc(var(--kronus-radius) + 4px)",
        "2xl": "calc(var(--kronus-radius) + 8px)",
        "3xl": "calc(var(--kronus-radius) + 14px)",
      },
      boxShadow: {
        xs: "var(--kronus-shadow-xs)",
        sm: "var(--kronus-shadow-sm)",
        md: "var(--kronus-shadow-md)",
        lg: "var(--kronus-shadow-lg)",
        glow: "var(--kronus-shadow-glow)",
      },
      fontFamily: {
        sans: "var(--kronus-font-sans)",
        display: "var(--kronus-font-display)",
        mono: "var(--kronus-font-mono)",
      },
      transitionTimingFunction: {
        "out-quart": "cubic-bezier(0.16, 1, 0.3, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
};

export default preset;
