/**
 * React-vs-Cronus parity scoreboard for the docs site.
 *
 * `scoreboard.json` is generated by `bun run audit:scoreboard -- --date <day>`
 * from the latest audit run and committed, so every page reading it renders
 * statically in production without a kernel. Server-only: never import this
 * from a client component (it would ship the JSON and zod).
 */
import { type FamilyScore, type Scoreboard, ScoreboardSchema } from "@cronus-ui/audit/scoreboard";
import raw from "./scoreboard.json";

export type { FamilyScore, Scoreboard };

export const SCOREBOARD: Scoreboard = ScoreboardSchema.parse(raw);

export type ScoreboardFilter = "all" | "diffs" | "not-ported";

export const SCOREBOARD_FILTERS: readonly { id: ScoreboardFilter; label: string }[] = [
  { id: "all", label: "All" },
  { id: "diffs", label: "Diffs" },
  { id: "not-ported", label: "Not ported" },
];

export function matchesFilter(family: FamilyScore, filter: ScoreboardFilter): boolean {
  if (filter === "diffs") return family.parity === "diff";
  if (filter === "not-ported") return family.status !== "ported";
  return true;
}

export function getFamilyScore(
  family: string,
  board: Scoreboard = SCOREBOARD,
): FamilyScore | undefined {
  return board.families.find((f) => f.family === family);
}

/**
 * Row link: the live React/Cronus split when a kernel audit origin is
 * configured (and the family has fixtures), otherwise the component docs.
 */
export function familyHref(family: FamilyScore, auditOrigin: string | null): string | null {
  if (auditOrigin && family.fixtures.length > 0) return `/audit/${family.family}`;
  if (family.component) return `/components/${family.family}`;
  return null;
}

type BadgeTone = "success" | "warning" | "destructive" | "info" | "secondary" | "outline";

export const PARITY_BADGE: Record<FamilyScore["parity"], { label: string; variant: BadgeTone }> = {
  match: { label: "Match", variant: "success" },
  diff: { label: "Diff", variant: "warning" },
  "not-run": { label: "Not run", variant: "secondary" },
  "not-ported": { label: "Not ported", variant: "outline" },
};

export const STATUS_BADGE: Record<FamilyScore["status"], { label: string; variant: BadgeTone }> = {
  ported: { label: "Ported", variant: "info" },
  stub: { label: "Stub", variant: "secondary" },
  "react-only": { label: "React only", variant: "outline" },
  unknown: { label: "Unknown", variant: "outline" },
};

const NOT_RUN = "—";

export function geometryText(score: FamilyScore["geometry"]): string {
  return score.status === "not-run" ? NOT_RUN : `${score.pass}/${score.pass + score.fail}`;
}

export function pixelText(score: FamilyScore["pixel"]): string {
  if (score.status === "not-run") return NOT_RUN;
  if (score.status === "fail") return "error";
  return `${score.diffPixels} px`;
}

export function logicText(score: FamilyScore["logic"]): string {
  return score.status === "not-run" ? NOT_RUN : `${score.pass}/${score.pass + score.fail}`;
}

/** Configured kernel audit origin, or null. `parseAuditOrigin` alone defaults to 5176. */
export function configuredAuditOrigin(
  raw: string | undefined,
  parse: (value: string) => string | null,
): string | null {
  return raw ? parse(raw) : null;
}
